name: java client test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: setup pulsar
        uses: shoothzj/setup-pulsar-action@v1
        env:
          PULSAR_PREFIX_ALLOW_AUTO_TOPIC_CREATION_TYPE: non-partitioned
          PULSAR_PREFIX_BROKER_ENTRY_METADATA_INTERCEPTORS: org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
          PULSAR_PREFIX_EXPOSING_BROKER_ENTRY_METADATA_TO_CLIENT_ENABLED: "true"
      - name: build image
        run: docker build . -t kop-integration-test
      - name: run kop
        run: docker run --name kop-integration-test -p 9092:9092 -d kop-integration-test
      - name: wait kop start
        uses: shoothzj/host-available-check-action@v1
        with:
          check_type: 'TCP'
          check_timeout: 60
          check_tcp_port: 9092
      - name: run java client test
        run: cd java-client-tests; mvn -B clean checkstyle:check test
